### ISSUE TITLE
Add tox-gh to conda-forge

### ISSUE THREAD

**Issue by Zeitsperre** [tox-dev/tox-gh#130]
Hi there,

Thanks for developing this plugin. Very helpful!

It would be great to have `tox-gh` on Conda-forge. Would this be something that the `tox` developers would be amenable to? I can open a draft PR if that's of interest.

Best

**Comment by gaborbernat** [comment]
This can be done without our involvement. You are welcome to add it to `conda-forge` yourself. Thanks!

**Comment by Zeitsperre** [comment]
Sounds good! For reference: https://github.com/conda-forge/staged-recipes/pull/27581
