### ISSUE TITLE
Support Python < 3.7

### ISSUE THREAD

**Issue by bittner** [tox-dev/tox-gh#61]
I understand that Python 2.7 is dead and Python 3 < 3.7 has been retired.

Tox is for test automation, though, and sometimes developers want to verify that their software continues to work even with outdated versions of Python.

The code base of this plugin is so small that it could do without features that require Python 3.7+ and even support Python 2.7 with rather little effort, no need even for `six` and friends. This would help!

**Comment by gaborbernat** [comment]
This is out of scope for this project. The better solution is to install this tool under the latest python version and then target the older version. That is install tox under 3.11 and then do tox -e py36, if you must support all, deprecated python.
