### ISSUE TITLE
Add a collapsible group for installation preliminaries

### ISSUE THREAD

**Issue by nedbat** [tox-dev/tox-gh#67]
When I look at my Action results now, I open the step and see this:  
<img width="686" alt="image" src="https://github.com/tox-dev/tox-gh/assets/23789/6eb01c1d-3d13-41d8-bfcf-5cd9f221b5b9">

All of the details of the package installations and other preliminaries are visible, but I have one more twisty to click open to see what actually happened with my tests.  I almost never want to see the stuff that is first visible, and always want to see the stuff that is hidden until I click.

Can we add another group so that at least the preliminaries are initially hidden? It would reduce the visual clutter, and put them on an even footing with the test running.

**Comment by gaborbernat** [comment]
That's a great idea, PR is welcome!
