### ISSUE TITLE
Question: How is this different from tox-gh-actions?

### ISSUE THREAD

**Issue by walles** [tox-dev/tox-gh#7]
Not an issue but a question: How is this project different from <https://github.com/ymyzk/tox-gh-actions>?

Right now the other project has a lot more stars and forks than this one.

What would be the upside to using this GitHub action rather than `tox-gh-actions`?

**Comment by gaborbernat** [comment]
This plugin is only compatible with the upcoming tox 4 version. They both do the same(ish) thing but they have a bit different design philosophies. For details why we have to https://github.com/ymyzk/tox-gh-actions/issues/74

> Right now the other project has a lot more stars and forks than this one.

You're free to use either one you like.

Notably https://github.com/ymyzk/tox-gh-actions#examples has different configuration format than https://github.com/tox-dev/tox-gh#basic-example

**Comment by nedbat** [comment]
@gaborbernat reading between the lines in https://github.com/ymyzk/tox-gh-actions/issues/74, it seems like there isn't going to be much effort to bring these two project back together?  Are you planning to fully support this plugin?

**Comment by gaborbernat** [comment]
Yes, there's no plan to unify the projects. I am planning on supporting this plugin (though is a community project, so PRs welcome).

**Comment by gaborbernat** [comment]
Is unclear to me what that is trying to do and how.

**Comment by henryiii** [comment]
I was trying to move in https://github.com/pytest-dev/pytest-github-actions-annotate-failures/pull/91. The idea is to be able to run just the "-pytestN" job but still keep the rest of the automatic selection.

**Comment by gaborbernat** [comment]
I do not think that is a feature we support today, but PR welcome.
